# Generated by Django 4.1.7 on 2023-04-13 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_specialists_alter_cosmetolog_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{8,15}$')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
