# Generated by Django 4.1.7 on 2023-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('issued', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
